# fly.toml app configuration file generated for moms-life on 2025-03-07T06:27:54-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'moms-life'
primary_region = 'dfw'
console_command = '/rails/bin/rails console'

[build]

[deploy]
  release_command = './bin/rails db:prepare'

[env]
  PORT = '8080'

[processes]
  app = "./bin/rails server -b 0.0.0.0 -p 8080"

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  # Adicionar um health check simples
  [[http_service.checks]]
    interval = '10s'
    timeout = '5s'
    grace_period = '30s'
    method = 'GET'
    path = '/up'
    protocol = 'http'
    tls_skip_verify = false

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
